
obj-$(CONFIG_RONGPIN_RP_POWER)		+= rp_power.o
# obj-$(CONFIG_RP_WAKE_LOCK)		+= rp_wake_lock.o
# CONFIG_GPIO_CTL does not exist in the 4,4 kernel tree.
obj-$(CONFIG_RONGPIN_GPIO_CTL)		+= rp_gpio_ctrl.o
# rp_config: I don't know what this is for, but it looks like it is for
# Android specific things - It stores or reads some configuration.
# obj-$(CONFIG_RP_CONFIG)  	+= rp_config.o
obj-$(CONFIG_RONGPIN_RP_GPIO)		+= rp_gpio.o

obj-$(CONFIG_RONGPIN_RP_LED)		+= rp_led.o
obj-$(CONFIG_RONGPIN_STM706)		+= stm706.o